db_config:
  host: 127.0.0.1
  user: root
  password: root
  prot: 3306
redis_config:
  host: 127.0.0.1
  auth: ~
  prot: 6379
master_pid: ~
worker_num: ~
daemon: false
log_path: ~
user_name: ~
password: ~