#路由配置,middleware可以不加
/:
  namespace: abundle
  controller: index
  action : index
  middleware: Pre@sss
/curl:
  namespace: abundle
  controller: index
  action : curl
  middleware: ~
/index:
  namespace: bbundle
  controller: index
  action : index
  middleware: ~
/select:
  namespace: abundle
  controller: index
  action : select
  middleware: Pre@select
/scanfFollowing:
  namespace: abundle
  controller: index
  action : scanfFollowing
  middleware: ~
